// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileHints } from "./ProfileHints";

export interface OAuthLoginResponse { accessToken?: string, refreshToken?: string, profile_hints: ProfileHints, }